name: Build

on:
  push:
    branches: [master]
    paths:
      - 'src/**/*'
      - 'projects/**/*'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci

      - name: build-lib
        run: npm run build

      - name: release
        if: github.ref == 'refs/heads/master'
        run: npm run semantic-release || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
